name: Build
on: [push, pull_request]
jobs:
  conda-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          python-version: 3.11
      - name: Build
        shell: bash -l {0}
        run: |
          conda install -y openturns pytest sphinx sphinx-gallery sphinx_rtd_theme numpydoc pandoc setuptools
          python setup.py install
          pytest
          sudo apt update -y && sudo apt install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
          make html -C doc
      - name: Upload
        if: ${{ github.ref == 'refs/heads/master' }}          
        run: |
          git clone --depth 1 https://${{ secrets.GH_TOKEN }}@github.com/m-balesdent/m-balesdent.github.io.git /tmp/io
          mkdir -p /tmp/io/otsmt/master
          cp -r doc/build/html/* /tmp/io/otsmt/master
          cd /tmp/io
          touch .nojekyll
          git config user.email "support@gh.com"
          git config user.name "GitHub Actions"
          git add -A .
          if test `git diff HEAD | wc -c` -eq 0; then exit 0; fi
          git commit -a -m "GitHub Actions build ${GITHUB_REPOSITORY} ${GITHUB_RUN_ID}"
          git push --quiet origin main > /dev/null 2>&1
